export type PermissionDefinition = {
  code: string;
  moduleKey: string;
  moduleLabel: string;
  label: string;
  description: string;
  available: boolean;
  assignable: boolean;
  visible: boolean;
};

export const PERMISSION_CATALOG = [
  {
    code: 'dashboard.read',
    moduleKey: 'dashboard',
    moduleLabel: 'Panel',
    label: 'Consultar el panel',
    description: 'Consultar el resumen y los avisos disponibles del negocio.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'configuration.read',
    moduleKey: 'configuration',
    moduleLabel: 'Configuración',
    label: 'Consultar la configuración',
    description: 'Consultar los datos generales y regionales de la empresa.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'configuration.update',
    moduleKey: 'configuration',
    moduleLabel: 'Configuración',
    label: 'Modificar la configuración',
    description: 'Cambiar los datos generales y regionales de la empresa.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'configuration.reset',
    moduleKey: 'configuration',
    moduleLabel: 'Configuración',
    label: 'Restablecer la configuración',
    description: 'Restablecer los ajustes de la empresa.',
    available: false,
    assignable: false,
    visible: true,
  },
  {
    code: 'users.read',
    moduleKey: 'users',
    moduleLabel: 'Usuarios',
    label: 'Consultar usuarios',
    description: 'Consultar las cuentas y su estado.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'users.manage',
    moduleKey: 'users',
    moduleLabel: 'Usuarios',
    label: 'Administrar cuentas existentes',
    description: 'Cambiar el estado de una cuenta y restablecer su acceso.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'roles.manage',
    moduleKey: 'roles',
    moduleLabel: 'Perfiles de acceso',
    label: 'Administrar perfiles de acceso',
    description: 'Crear perfiles y asignarlos a las cuentas de la empresa.',
    available: true,
    assignable: false,
    visible: true,
  },
  {
    code: 'sessions.read',
    moduleKey: 'sessions',
    moduleLabel: 'Sesiones',
    label: 'Consultar sesiones activas',
    description: 'Consultar los dispositivos con una sesión abierta.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'sessions.revoke',
    moduleKey: 'sessions',
    moduleLabel: 'Sesiones',
    label: 'Cerrar sesiones de otras cuentas',
    description: 'Cerrar el acceso abierto de otra cuenta.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'products.read',
    moduleKey: 'products',
    moduleLabel: 'Catálogo',
    label: 'Consultar productos',
    description: 'Consultar productos, categorías y precios.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'products.manage',
    moduleKey: 'products',
    moduleLabel: 'Catálogo',
    label: 'Crear y editar productos',
    description: 'Crear categorías y productos, y modificar sus datos.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'products.prices.manage',
    moduleKey: 'products',
    moduleLabel: 'Catálogo',
    label: 'Administrar precios',
    description: 'Modificar precios de productos.',
    available: false,
    assignable: false,
    visible: true,
  },
  {
    code: 'inventory.read',
    moduleKey: 'inventory',
    moduleLabel: 'Inventario',
    label: 'Consultar existencias',
    description: 'Consultar saldos y disponibilidad de productos.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'inventory.receive',
    moduleKey: 'inventory',
    moduleLabel: 'Inventario',
    label: 'Recibir mercancía',
    description: 'Registrar mercancía recibida.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'inventory.adjust',
    moduleKey: 'inventory',
    moduleLabel: 'Inventario',
    label: 'Ajustar existencias',
    description: 'Registrar aumentos o disminuciones de existencias.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'inventory.threshold.update',
    moduleKey: 'inventory',
    moduleLabel: 'Inventario',
    label: 'Modificar niveles de alerta',
    description: 'Cambiar los niveles usados para alertas de inventario.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'customers.read',
    moduleKey: 'customers',
    moduleLabel: 'Clientes',
    label: 'Consultar clientes',
    description: 'Consultar la información de clientes.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'customers.manage',
    moduleKey: 'customers',
    moduleLabel: 'Clientes',
    label: 'Administrar clientes',
    description: 'Crear y modificar cuentas de clientes.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'suppliers.read',
    moduleKey: 'suppliers',
    moduleLabel: 'Proveedores',
    label: 'Consultar proveedores',
    description: 'Consultar la información de proveedores.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'suppliers.manage',
    moduleKey: 'suppliers',
    moduleLabel: 'Proveedores',
    label: 'Administrar proveedores',
    description: 'Crear y modificar cuentas de proveedores.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'sales.read',
    moduleKey: 'sales',
    moduleLabel: 'Ventas',
    label: 'Consultar ventas',
    description: 'Consultar las ventas registradas.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'sales.create',
    moduleKey: 'sales',
    moduleLabel: 'Ventas',
    label: 'Registrar ventas',
    description: 'Registrar ventas y sus comprobantes.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'sales.cancel',
    moduleKey: 'sales',
    moduleLabel: 'Ventas',
    label: 'Cancelar ventas',
    description: 'Cancelar ventas registradas.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'sales.return',
    moduleKey: 'sales',
    moduleLabel: 'Ventas',
    label: 'Registrar devoluciones',
    description: 'Registrar devoluciones de ventas.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'payments.read',
    moduleKey: 'payments',
    moduleLabel: 'Pagos',
    label: 'Consultar pagos',
    description: 'Consultar los pagos registrados.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'payments.confirm',
    moduleKey: 'payments',
    moduleLabel: 'Pagos',
    label: 'Confirmar pagos',
    description: 'Confirmar pagos recibidos.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'reports.read',
    moduleKey: 'reports',
    moduleLabel: 'Reportes',
    label: 'Consultar reportes',
    description: 'Consultar reportes disponibles para la empresa.',
    available: false,
    assignable: false,
    visible: false,
  },
  {
    code: 'audit.read',
    moduleKey: 'audit',
    moduleLabel: 'Actividad',
    label: 'Consultar actividad administrativa',
    description: 'Consultar cambios y acciones administrativas.',
    available: true,
    assignable: true,
    visible: true,
  },
  {
    code: 'system_health.read',
    moduleKey: 'system_health',
    moduleLabel: 'Diagnóstico',
    label: 'Consultar el estado técnico',
    description: 'Consultar información técnica de salud del sistema.',
    available: false,
    assignable: false,
    visible: false,
  },
] as const satisfies readonly PermissionDefinition[];

export type PermissionCode = (typeof PERMISSION_CATALOG)[number]['code'];
